### ISSUE TITLE
Synapse: can't get 2nd source (audio_blrms) to work

### ISSUE THREAD

**Issue by rxa254** [rxa254/MoodCube#1]
I've modified __main__.py to add audio_blrms.py as another source but no work. If I comment out the import of audio_blrms, it still works as normal for audio.py, but I can't get it to work for audio_blrms by itself or for both of them. Some config and syntax help?

**Comment by jrollins** [comment]
the module was calling argparse.parse_args at the top level, which was eating all command line arguments for __main__.  i moved the arg parsing into main() so that it's only called when you're running the module directly.

When running in the actual pipeline you can pass args when specifying the element:

$ python -m synapse audio_blrms:44100

but the defaults should be correct:

$ python -m synapse audio_blrms

**Comment by rxa254** [comment]
thanks, that works. But now the args get eaten by audio.py instead of going to audio_blrms.py. How to get verbose flag to work for audio_blrms?

**Comment by rxa254** [comment]
this was some weirdness in argparsing. The arguments go to synapse, not to the sub functions, so we'd have to pass verbose to audio_blrms for that.

Instead, I just changed the statements to logging.info or logging.debug to make it print.
